name: k6 Performance Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 performance test
        uses: grafana/run-k6-action@v1
        with:
          path: ./bottleneck-demo.js
          debug: true
